// Redeven keeps the runtime/API layer local, but the canonical Notes DSL and
// projection helpers are published upstream from floe-webapp-core/notes.
// Re-export them here so existing Redeven imports stay stable without
// maintaining a second copy of the Notes UI contract.
export {
  NOTE_BUCKET_METRICS,
  NOTE_COLOR_TOKENS,
  NOTES_SCALE_MAX,
  NOTES_SCALE_MIN,
  TOPIC_ACCENT_TOKENS,
  TOPIC_ICON_KEYS,
  applyNotesEvent,
  centerViewportOnWorldPoint,
  clampScale,
  computeBoardBounds,
  createDefaultNotesSnapshot,
  groupTrashItems,
  mergeBoardBounds,
  normalizeNotesSnapshot,
  noteBucketMetrics,
  promoteLocalItem,
  removeSnapshotItem,
  replaceSnapshotItem,
  replaceSnapshotTopic,
  replaceSnapshotTrashItem,
  screenToWorld,
  visibleWorldRect,
  worldToScreen,
  zoomViewportAtPoint,
  type NoteColorToken,
  type NotesConnectionState,
  type NotesController,
  type NotesCreateNoteInput,
  type NotesCreateTopicInput,
  type NotesEvent,
  type NotesItem,
  type NotesItemMetrics,
  type NotesPoint,
  type NotesRect,
  type NotesSizeBucket,
  type NotesSnapshot,
  type NotesTopic,
  type NotesTrashGroup,
  type NotesTrashItem,
  type NotesUpdateNoteInput,
  type NotesUpdateTopicInput,
  type NotesViewport,
  type TopicAccentToken,
  type TopicIconKey,
} from '@floegence/floe-webapp-core/notes';
