#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." &> /dev/null && pwd)
GEN_ROOT="$ROOT_DIR/internal/knowledge/generated"

[ -f "$GEN_ROOT/knowledge_lock.json" ] || { echo "missing knowledge_lock.json" >&2; exit 1; }
[ -f "$GEN_ROOT/generation_report.json" ] || { echo "missing generation_report.json" >&2; exit 1; }
[ -f "$GEN_ROOT/indices/topic_index.yaml" ] || { echo "missing topic_index.yaml" >&2; exit 1; }
[ -f "$GEN_ROOT/indices/code_index.yaml" ] || { echo "missing code_index.yaml" >&2; exit 1; }

CARD_COUNT=$(find "$GEN_ROOT/cards" -maxdepth 1 -type f -name "*.md" | wc -l | tr -d " ")
if [ "$CARD_COUNT" -lt 1 ]; then
  echo "no generated cards found" >&2
  exit 1
fi

REDEVEN_AGENT_ROOT="$ROOT_DIR" python3 - <<"PY"
import hashlib
import json
import os
import sys

root_dir = os.environ.get("REDEVEN_AGENT_ROOT", "").strip()
if not root_dir:
    print("missing REDEVEN_AGENT_ROOT", file=sys.stderr)
    sys.exit(1)
root = os.path.join(root_dir, "internal", "knowledge", "generated")
lock_path = os.path.join(root, "knowledge_lock.json")
with open(lock_path, "r", encoding="utf-8") as f:
    lock = json.load(f)

if lock.get("generator", {}).get("engine", "") != "flower-local":
    print("knowledge lock must be generated by flower-local", file=sys.stderr)
    sys.exit(1)

files = []
for dirpath, _, filenames in os.walk(root):
    for name in filenames:
        rel = os.path.relpath(os.path.join(dirpath, name), root).replace("\\", "/")
        if rel == "knowledge_lock.json":
            continue
        files.append(rel)
files.sort()

h = hashlib.sha256()
for rel in files:
    with open(os.path.join(root, rel), "rb") as f:
        payload = f.read()
    h.update(rel.encode("utf-8"))
    h.update(b"\n")
    h.update(payload)
    h.update(b"\n")

got = h.hexdigest()
want = str(lock.get("outputs_sha256", "")).strip()
if not want:
    print("knowledge lock missing outputs_sha256", file=sys.stderr)
    sys.exit(1)
if got != want:
    print("knowledge generated outputs hash mismatch", file=sys.stderr)
    print(f"want={want}", file=sys.stderr)
    print(f"got ={got}", file=sys.stderr)
    sys.exit(1)
PY
