// Simple generator to embed scripts/install.sh into a Cloudflare Worker.
// This script reads the install.sh from the repo root and produces
// dist/install-worker.mjs in this directory.

const fs = require("fs");
const path = require("path");

function main() {
  try {
    const here = __dirname;
    const repoRoot = path.resolve(here, "../../../..");

    const sourcePath = path.join(repoRoot, "scripts", "install.sh");
    const outDir = path.join(here, "dist");
    const outPath = path.join(outDir, "install-worker.mjs");

    if (!fs.existsSync(sourcePath)) {
      console.error("ERROR: scripts/install.sh not found at", sourcePath);
      process.exit(1);
    }

    const script = fs.readFileSync(sourcePath, "utf8");

    const generated = `// Auto-generated from scripts/install.sh
// Do not edit this file manually. Run generate-worker.js instead.
const INSTALL_SCRIPT = ${JSON.stringify(script)};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname !== "/install.sh") {
      // For all other paths, fall back to the origin.
      return fetch(request);
    }

    return new Response(INSTALL_SCRIPT, {
      status: 200,
      headers: {
        "Content-Type": "text/x-shellscript; charset=utf-8",
        "Content-Disposition": "inline; filename=\\"install.sh\\"",
        // Cache at the edge and in browsers for 10 minutes by default.
        "Cache-Control": "public, max-age=600, s-maxage=600",
      },
    });
  },
};
`;

    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(outPath, generated, "utf8");

    console.log("Generated Worker source at", outPath);
  } catch (err) {
    console.error("Failed to generate Worker source:", err);
    process.exit(1);
  }
}

main();

