#!/bin/sh
set -eu

release_tag="${1:-${RELEASE_TAG:-}}"
output_path="${2:-${RELEASE_NOTES_PATH:-dist/RELEASE_NOTES.md}}"
repo="${GITHUB_REPOSITORY:-floegence/redeven-agent}"
install_script_url="${INSTALL_SCRIPT_URL:-https://install.example.invalid/install.sh}"
version_manifest_url="${VERSION_MANIFEST_URL:-https://version.agent.example.invalid/v1/manifest.json}"

validate_release_tag() {
  case "$1" in
    v[0-9]*.[0-9]*.[0-9]*|v[0-9]*.[0-9]*.[0-9]*-[0-9A-Za-z.-]*|v[0-9]*.[0-9]*.[0-9]*+[0-9A-Za-z.-]*|v[0-9]*.[0-9]*.[0-9]*-[0-9A-Za-z.-]*+[0-9A-Za-z.-]*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

if [ -z "$release_tag" ]; then
  echo "release tag is required (arg1 or RELEASE_TAG)" >&2
  exit 1
fi

if ! validate_release_tag "$release_tag"; then
  echo "invalid release tag: $release_tag" >&2
  exit 1
fi

output_dir=$(dirname "$output_path")
mkdir -p "$output_dir"

release_date=$(date -u +"%Y-%m-%d")
release_url="https://github.com/${repo}/releases"
compare_line=""

if git rev-parse --git-dir >/dev/null 2>&1; then
  previous_tag=$(git tag -l "v*" --sort=-version:refname | awk -v current="$release_tag" '$0 != current {print; exit}')
  if [ -n "$previous_tag" ]; then
    compare_url="https://github.com/${repo}/compare/${previous_tag}...${release_tag}"
    compare_line="- Full commit diff: [${previous_tag}...${release_tag}](${compare_url})"
  fi
fi

cat > "$output_path" <<NOTES
## Release Overview

- Version: \`${release_tag}\`
- Release date (UTC): ${release_date}
- Primary package source: GitHub Release assets (Cloudflare mirror sync runs after release)

## Install / Upgrade

Pinned install:

\`\`\`bash
curl -fsSL ${install_script_url} | REDEVEN_VERSION=${release_tag} sh
\`\`\`

Upgrade an existing agent in place:

\`\`\`bash
curl -fsSL ${install_script_url} | REDEVEN_INSTALL_MODE=upgrade REDEVEN_VERSION=${release_tag} sh
\`\`\`

## Binary Assets

- \`redeven_linux_amd64.tar.gz\`
- \`redeven_linux_arm64.tar.gz\`
- \`redeven_darwin_amd64.tar.gz\`
- \`redeven_darwin_arm64.tar.gz\`
- \`SHA256SUMS\` + \`SHA256SUMS.sig\` + \`SHA256SUMS.pem\`

## Verify Integrity (recommended)

\`\`\`bash
curl -fLO ${release_url}/download/${release_tag}/SHA256SUMS
curl -fLO ${release_url}/download/${release_tag}/SHA256SUMS.sig
curl -fLO ${release_url}/download/${release_tag}/SHA256SUMS.pem

cosign verify-blob \\
  --certificate SHA256SUMS.pem \\
  --signature SHA256SUMS.sig \\
  --certificate-identity-regexp '^https://github.com/floegence/redeven-agent/.github/workflows/release\.yml@refs/tags/v.*$' \\
  --certificate-oidc-issuer https://token.actions.githubusercontent.com \\
  SHA256SUMS

sha256sum -c SHA256SUMS
\`\`\`

## Notes For Operators

- Installer download order: GitHub Release first, Cloudflare package mirror fallback.
- Version manifest endpoint: ${version_manifest_url}
- If you need deployment details, see \`docs/RELEASE.md\` in this repository.
${compare_line}

---

## Auto-generated change list

The section below is generated by GitHub from merged pull requests and commits.
NOTES

printf '%s\n' "release notes written to $output_path"
